-- CREAR TABLA 
CREATE TABLE USUARIO (
	USUARIO VARCHAR2(400),
	CORREO VARCHAR2(300) NOT NULL,
	ADD_FECHA DATE DEFAULT SYSDATE,
	PRIMARY KEY(USUARIO)
);

CREATE TABLE CUENTA_TIPO (
	CUENTA_TIPO NUMBER,
	DESCRIPCION VARCHAR2(300) NOT NULL UNIQUE,
	ADD_FECHA DATE DEFAULT SYSDATE,
	PRIMARY KEY(CUENTA_TIPO)
);

CREATE TABLE MONEDA (
	MONEDA NUMBER, 
	DESCRIPCION VARCHAR2(10) NOT NULL UNIQUE,
	ADD_FECHA DATE DEFAULT SYSDATE,
	PRIMARY KEY(MONEDA)
);

CREATE TABLE CUENTA (
	CUENTA NUMBER,
	DESCRIPCION VARCHAR2(400) NOT NULL,
	CUENTA_TIPO NUMBER NOT NULL,
	MONEDA NUMBER NOT NULL,
	USUARIO VARCHAR2(400) NOT NULL,
	ADD_FECHA DATE DEFAULT SYSDATE,
	PRIMARY KEY(CUENTA),
	FOREIGN KEY(MONEDA) REFERENCES MONEDA(MONEDA),
	FOREIGN KEY(CUENTA_TIPO) REFERENCES CUENTA_TIPO(CUENTA_TIPO),
	FOREIGN KEY(USUARIO) REFERENCES USUARIO(USUARIO)
);

COMMIT;

-- SEQUENCIAS 

CREATE SEQUENCE SQ_CUENTA_TIPO NOCACHE;

CREATE SEQUENCE SQ_MONEDA NOCACHE;

CREATE SEQUENCE SQ_CUENTA NOCACHE;

COMMIT;

-- INSERTS 
INSERT INTO MONEDA(MONEDA, DESCRIPCION) 
VALUES (SQ_MONEDA.NEXTVAL, 'GTQ');

INSERT INTO MONEDA(MONEDA, DESCRIPCION) 
VALUES (SQ_MONEDA.NEXTVAL, 'USD');

INSERT INTO CUENTA_TIPO(CUENTA_TIPO, DESCRIPCION) 
VALUES (SQ_CUENTA_TIPO.NEXTVAL, 'Efectivo');

INSERT INTO CUENTA_TIPO(CUENTA_TIPO, DESCRIPCION) 
VALUES (SQ_CUENTA_TIPO.NEXTVAL, 'Corriente');

INSERT INTO CUENTA_TIPO(CUENTA_TIPO, DESCRIPCION) 
VALUES (SQ_CUENTA_TIPO.NEXTVAL, 'Ahorro');

COMMIT;

-- SELECTS
SELECT * FROM MONEDA;

SELECT * FROM CUENTA_TIPO;

SELECT * FROM USUARIO;

SELECT * FROM CUENTA;

COMMIT;

-- DROP
DROP TABLE CUENTA;

DROP TABLE MONEDA;

DROP TABLE CUENTA_TIPO;

DROP TABLE USUARIO;

DROP SEQUENCE SQ_CUENTA_TIPO;

DROP SEQUENCE SQ_MONEDA;

DROP SEQUENCE SQ_CUENTA;

COMMIT;